In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from numpy.linalg import eigvals
from numpy.linalg import eig


In [2]:
# Load CSV file into a numpy array
X = np.genfromtxt("./data/Ex2_data.csv", delimiter=",")

# Print the data
print(f"X is:\n{X}")


X is:
[[ 1.  1.  3.]
 [-1. -1.  3.]
 [ 1.  1. -3.]
 [-1. -1. -3.]
 [ 1. -1.  0.]
 [-1.  1.  0.]]


In [3]:
# 1. Determine the standardized data matrix Z.
scaler = StandardScaler()
Z = scaler.fit_transform(X)

print(f"The standardized data matrix Z is:\n{Z}")


The standardized data matrix Z is:
[[ 1.          1.          1.22474487]
 [-1.         -1.          1.22474487]
 [ 1.          1.         -1.22474487]
 [-1.         -1.         -1.22474487]
 [ 1.         -1.          0.        ]
 [-1.          1.          0.        ]]


In [4]:
# 2. Deduce the correlation matrix Rx.
n = Z.shape[0]

Rx = np.corrcoef(Z, rowvar=False)

print(f"The correlation matrix Rx is:\n{Rx}")

The correlation matrix Rx is:
[[1.         0.33333333 0.        ]
 [0.33333333 1.         0.        ]
 [0.         0.         1.        ]]


In [5]:
# 3. Determine the spectrum of Rx.
spectrum = eigvals(Rx)

print(f"The spectrum of Rx is:\n{spectrum}")


The spectrum of Rx is:
[1.33333333 0.66666667 1.        ]


In [6]:
# 4. Deduce the principle components matrix CX.
# We first determine the eigenvectors of the matrix RX and sort the eigenvalues in descending order and arrange the eigenvectors accordingly.
eigenvalues, eigenvectors = eig(Rx)
print(f"The eigenvalues here are unsorted:\n{eigenvalues}")


The eigenvalues here are unsorted:
[1.33333333 0.66666667 1.        ]


In [7]:
# Sorting the eigenvalues and rearranging the eigenvectors.
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print(f"The eigenvalues are:\n{eigenvalues}")


The eigenvalues are:
[1.33333333 1.         0.66666667]


In [8]:
# Given the eigenvalues above, we can chose how many principle components to retain by keeping the ones who's eigenvalues are >= 1
to_keep = [f"PC{i + 1}" for i, x in enumerate(eigenvalues) if x >= 1]
print(f"The principle components to keep are:\n{to_keep}")


The principle components to keep are:
['PC1']


In [9]:
print(f"The eigenvectors are:\n{eigenvectors}")


The eigenvectors are:
[[ 0.70710678  0.         -0.70710678]
 [ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]]


In [10]:
Cx = Z @ eigenvectors
print(f"The principle components matrix Cx is:\n{Cx}")


The principle components matrix Cx is:
[[ 1.41421356e+00  1.22474487e+00  1.11022302e-16]
 [-1.41421356e+00  1.22474487e+00 -1.11022302e-16]
 [ 1.41421356e+00 -1.22474487e+00  1.11022302e-16]
 [-1.41421356e+00 -1.22474487e+00 -1.11022302e-16]
 [ 1.11022302e-16  0.00000000e+00 -1.41421356e+00]
 [-1.11022302e-16  0.00000000e+00  1.41421356e+00]]


In [11]:
# 5. Decide how many principle components we should retain. Justify your decision.
# We'll use the Proportion of the total variance criterion method this time with a threshold of 75%.
cumulative_variance = np.cumsum(eigenvalues) / np.sum(eigenvalues)
print(f"The cumulative variance is:\n{cumulative_variance}")
n_components = np.argmax(cumulative_variance >= 0.75) + 1
print(f"Number of principal components to retain: {n_components}")


The cumulative variance is:
[0.44444444 0.77777778 1.        ]
Number of principal components to retain: 2


In [12]:
# 6. Say whether we were able to predict the result of PCA earlier.
if len(to_keep) == n_components:
    print(
        "Our predictions were right! The proportion of the total variance criterion and the eigenvalue criterion were equivalent in this case."
    )
else:
    print(
        "Our predictions were wrong! The proportion of the total variance criterion and the eigenvalue criterion were not equivalent in this case."
    )

Our predictions were wrong! The proportion of the total variance criterion and the eigenvalue criterion were not equivalent in this case.
